name: Snyk Scanning 
on: [push]
# on:
#     push:
#         branches: [ feature ]
#     pull_request:
#         branches: [ feature ]
jobs:
    build:
        runs-on: ubuntu-latest
        # strategy:
        #     matrix:
        #         node-version: [20]
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        # - name: Set up Node.js
        #   uses: actions/setup-node@v2
        #   with:
        #     node-version: ${{ matrix.node-version }}
        # - name: Install dependencies
        #   run: npm install
        - name: Run tests
          run: npm test
    security:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
              SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#
#
#
#

