name: Snyk Scanning 
on: [push]

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: npm dependencies
          run: npm install     

        - name: Run Snyk to check for vulnerabilities (SCA - third party)
          uses: snyk/actions/node@master
          with:
            args: --severity-threshold=high
          env:
              SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
